server:
  port: 90

datasource:
  host: "sgp-processor-svc.csntzsasnlad.us-east-1.rds.amazonaws.com:3306"
  user: "sgpprocessorsvc"
  pass: "test1234"
  dbname: "sgp_processor_svc"

queue-bot-process:
  activebot: true
  dateLocalFormat: "America/New_York"
  time-run: "1m"


service:
  sgp-info-svc:
    getDataHistorical: "http://54.91.225.24:30001/v1/sgp-info-svc/getDataHistorical"
