server:
  port: 91

datasource:
  host: "localhost:3306"
  user: "root"
  pass: "12345"
  dbname: "sgp_processor_svc"

queue-bot-process:
  activebot: true
  dateLocalFormat: "America/El_Salvador"
  time-run: "10m"


service:
  sgp-info-svc:
    getDataHistorical: "http://localhost:90/v1/sgp-info-svc/getDataHistorical"